// src/views/Login.vue
<template>
  <div class="min-h-screen bg-[#F9F8F6] flex items-center justify-center p-4">
    <div class="w-full max-w-md">
      <div class="text-center mb-8">
        <img src="/src/assets/img/awac.png" alt="AWAC MONO" class="h-16 mx-auto mb-4" />
        <h1 class="text-2xl font-heading font-black text-gray-900">AWAC MONO</h1>
        <p class="text-sm text-gray-500">Administration</p>
      </div>

      <div class="bg-white/80 backdrop-blur-xl rounded-3xl border border-white/30 shadow-2xl p-6 md:p-8">
        <h2 class="text-xl font-heading font-black text-gray-900 mb-6">Connexion</h2>

        <form @submit.prevent="handleLogin" class="space-y-4">
          <div>
            <label class="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Identifiant ou Email</label>
            <input
              v-model="loginInput"
              type="text"
              required
              autocomplete="username"
              class="w-full px-4 py-2.5 rounded-xl border border-gray-200 focus:border-awac-primary focus:ring-2 focus:ring-awac-primary/20 outline-none transition-all bg-white/50"
              placeholder="admin ou admin@awac.local"
            />
          </div>

          <div>
            <label class="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Mot de passe</label>
            <input
              v-model="password"
              type="password"
              required
              autocomplete="current-password"
              class="w-full px-4 py-2.5 rounded-xl border border-gray-200 focus:border-awac-primary focus:ring-2 focus:ring-awac-primary/20 outline-none transition-all bg-white/50"
              placeholder="••••••••"
            />
          </div>

          <div class="flex items-center justify-between">
            <label class="flex items-center gap-2 text-sm text-gray-600 cursor-pointer">
              <input type="checkbox" v-model="rememberMe" class="accent-awac-primary" />
              Se souvenir de moi
            </label>
          </div>

          <button
            type="submit"
            :disabled="loading"
            class="w-full py-3 bg-awac-primary text-white font-semibold rounded-xl hover:bg-awac-primary/90 transition-colors shadow-sm flex items-center justify-center gap-2 disabled:opacity-70"
          >
            <span v-if="loading" class="animate-spin w-4 h-4 border-2 border-white border-t-transparent rounded-full"></span>
            {{ loading ? 'Connexion...' : 'Se connecter' }}
          </button>

          <p v-if="error" class="text-sm text-red-500 text-center">{{ error }}</p>
          <p v-if="debugInfo" class="text-xs text-gray-400 text-center">{{ debugInfo }}</p>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { supabase } from '@/services/supabase'
import { useUserStore } from '@/stores/userStore'

const router = useRouter()
const userStore = useUserStore()

const loginInput = ref('admin')
const password = ref('Admin123!')
const rememberMe = ref(false)
const loading = ref(false)
const error = ref('')
const debugInfo = ref('')

const handleLogin = async () => {
  error.value = ''
  debugInfo.value = ''
  loading.value = true

  try {
    let email = loginInput.value.trim()
    if (!email.includes('@')) {
      email = `${email}@awac.local`
    }

    debugInfo.value = `Tentative avec: ${email}`

    const { data, error: signInError } = await supabase.auth.signInWithPassword({
      email: email,
      password: password.value,
    })

    if (signInError) {
      debugInfo.value = `Erreur: ${signInError.message}`
      throw signInError
    }

    debugInfo.value = `✅ Connecté: ${data.user.email}`

    if (rememberMe.value) {
      localStorage.setItem('awac_remember_me', 'true')
    } else {
      localStorage.removeItem('awac_remember_me')
    }

    await userStore.fetchUser()
    router.push('/admin')
  } catch (err) {
    console.error('Erreur de connexion:', err)
    error.value = err.message || 'Identifiants incorrects. Vérifiez votre identifiant et votre mot de passe.'
  } finally {
    loading.value = false
  }
}
</script>

// src/routes/admin/login.tsx
import { useState, type FormEvent } from 'react'
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { loginAdmin } from '../../hooks/useAdminProfile'
import { ApiError } from '../../utils/api'
import awacLogo from '../../assets/awac.png'

export const Route = createFileRoute('/admin/login')({
  component: AdminLogin,
})

const FIELD_CLASS =
  'w-full px-4 py-2.5 rounded-xl border border-gray-200 focus:border-awac-primary focus:ring-2 focus:ring-awac-primary/20 outline-none transition-all text-sm'
const LABEL_CLASS = 'block text-xs font-semibold text-gray-500 uppercase tracking-wider'

function AdminLogin() {
  const navigate = useNavigate()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')

  const submitLogin = async (event: FormEvent) => {
    event.preventDefault()
    setSubmitting(true)
    setErrorMessage('')
    try {
      await loginAdmin(email, password)
      void navigate({ to: '/admin' })
    } catch (error) {
      // Le 429 vient du limiteur de tentatives : distinguer les deux messages
      // évite de faire croire à un mot de passe faux après un blocage.
      const status = error instanceof ApiError ? error.status : undefined
      setErrorMessage(
        status === 429
          ? 'Trop de tentatives — réessayez dans quelques minutes.'
          : 'Identifiants invalides.',
      )
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="min-h-screen bg-awac-dark flex items-center justify-center px-6 selection:bg-awac-primary/20">
      <div className="w-full max-w-sm space-y-8">
        <div className="text-center space-y-3">
          <img src={awacLogo} alt="AWAC" className="h-16 w-auto mx-auto brightness-0 invert" />
          <h1 className="text-white font-heading font-black text-2xl tracking-tight uppercase">
            Espace admin
          </h1>
          <p className="text-white/50 font-sans text-sm">Awards des Couturier·e·s du Mono</p>
        </div>

        <form
          className="bg-white rounded-[2.5rem_0_2.5rem_0] shadow-2xl p-8 space-y-5"
          onSubmit={submitLogin}
        >
          <div className="space-y-1">
            <label htmlFor="admin-email" className={LABEL_CLASS}>
              Email
            </label>
            <input
              id="admin-email"
              value={email}
              onChange={(event) => setEmail(event.target.value)}
              type="email"
              autoComplete="username"
              required
              className={FIELD_CLASS}
            />
          </div>

          <div className="space-y-1">
            <label htmlFor="admin-password" className={LABEL_CLASS}>
              Mot de passe
            </label>
            <input
              id="admin-password"
              value={password}
              onChange={(event) => setPassword(event.target.value)}
              type="password"
              autoComplete="current-password"
              required
              className={FIELD_CLASS}
            />
          </div>

          {errorMessage ? (
            <p className="text-sm text-red-500" role="alert">
              {errorMessage}
            </p>
          ) : null}

          <button type="submit" disabled={submitting} className="btn-awac w-full text-[11px] py-3.5">
            {submitting ? (
              <span className="animate-spin w-4 h-4 border-2 border-white border-t-transparent rounded-full" />
            ) : null}
            {submitting ? 'Connexion…' : 'Se connecter'}
          </button>
        </form>
      </div>
    </div>
  )
}
